version: "3.8"
services:
  nginx:
    depends_on:
      - client
      - signaling
    restart: always
    build:
      context: ./nginx
    ports:
      - "3050:80"
  client:
    stdin_open: true
    build:
      context: ./client
    volumes:
      - ./client:/app
  signaling:
    build:
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app